schema_version: 1
geometry_id: ParallelPlateCapacitor
mesh:
  path: /work/geometry/COMSOLValidation/parallel_plate_capacitor/mesh/mesh22.msh
  geom_volt_path_overwrite: /work/geometry/COMSOLValidation/parallel_plate_capacitor/
  is_tpc: false
  mark_external_boundary: true
  external_boundary_name: BC_Outer
  split_axis_boundary: false
  geometry: parallel
  voltages: parallel
  liquid_level: 0.004
  shrinkage_factor: 1
  manual_naming_only: true
  autoappend: false
  append_fieldShaping_Voltages_toConfig: false
  NetgenParams:
    debugCoarse: false
    maxSize: 0.015
    minSize: 3.0e-06
    growthRate: 0.1
    UseSurfaceCurvature: 1
    NBSegmentsPerEdge: 4
    NBSegmentsPerRadius: 5
    UseChordalError: 0
    ChordalErrorValue: 1
    AQ_ElemSizeWeight: 0.5
    AQ_UseDelauney: 1
    AQ_CheckOverlapping: 1
    AQ_CheckChartBoundary: 1
    AQ_FuseEdges: 1
    Opt_QuadAllowed: false
    Opt_SecondOrder: 0
    Opt_Optimize: true
  AMR:
    enable: true
    max_iter: 100
    local_error_goal: 1e-7
    total_error_goal: 0.0
    total_error_fraction: 0.0
    total_error_norm_p: 2.0
    enable_derefine: true
    derefine_hysterisis: 0.5
    derefine_op: 2
    max_elements: 0
    max_dofs: 0
    nc_limit: 0
    prefer_conforming_refinement: true
    min_marked_elements: 1
    min_rel_error_reduction: 0.0
    estimator: Kelly
    enable_rebalance: true
    verbose: false
    save_serial: true
save_path: /work/sim_results/parallel_plate_capacitor_results/
delete_files_present: true
interpolate:
  Nx: 1000
  Ny: 1000
  x_min: -0.5
  x_max: 0.5
  y_min: -0.5
  y_max: 0.5
  V: true
  E: true
  code1_mode: nan
solver:
  solver: MUMPS
  generate_E: false
  axisymmetric: false
  order: 2
  assembly_mode: partial
  maxiter: 100000
  printlevel: 0
materials:
  GXe:
    epsilon_r: 1.95
    attr_id: 1
  LXe:
    epsilon_r: 1.0
    attr_id: 2
  PTFE:
    epsilon_r: 10000
    attr_id: 3
boundaries:
  BC_BottomPlate:
    bdr_id: 4
    type: dirichlet
    value: 0.0
  BC_TopPlate:
    bdr_id: 5
    type: dirichlet
    value: 100.0
  BC_Outer:
    bdr_id: 6
    type: dirichlet
    value: 50.0